### ISSUE TITLE
cannot import modules with dash

### ISSUE THREAD

**Issue by MirKml** [vlisivka/bash-modules#22]
There is problem when the bash module name has dash inside. I thinks it's pretty common to have bash script file names with dash e.g. `deployment-app.sh`.
When I want to use this scripts as bash module with import.sh. It doesn't work
`source import.sh deployment-app` throws error
`....lib/import.sh: line 139: local: __deployment-app__DEFINED': invalid variable name for name reference`

Handy library anyway :-)

**Comment by vlisivka** [comment]
Fixed. See https://github.com/vlisivka/bash-modules/commit/db853fe33845c23b58ee4ee3c654f708c887d178 .
